from chat_history.database import get_database
from chat_history.models.request import ConversationModel, ConversationItem
from chat_history.services.request_service import ConversationService
from fastapi import APIRouter, HTTPException, Depends


router = APIRouter()


@router.post("/", response_model=ConversationModel, status_code=200)
async def add_conversation_item(
    username: str, conversation_item: ConversationItem, db=Depends(get_database)
):
    """
    Add a new conversation item to the existing conversation

    - **username**: Username of the user making the request
    - **question**: Question or content of the request
    - **answer**: Answer provided to the user
    - **timestamp**: Date and time of the conversation item (autogenerated if not provided)

    Returns the updated conversation with the new item added
    """
    conversation_service = ConversationService(db)

    updated_conversation = await conversation_service.add_conversation_item(
        username, conversation_item
    )

    return updated_conversation


@router.get("/{username}", response_model=ConversationModel)
async def get_user_conversation(username: str, db=Depends(get_database)):
    """
    Get the conversation history of a user

    - **username**: Username of the user whose conversation history to retrieve

    Returns the conversation history
    """
    conversation_service = ConversationService(db)

    conversation = await conversation_service.get_conversation_by_username(username)

    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")

    return conversation
